version: '3.8'

services:
  # Frontend Application
  draftly-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: draftly-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      HOSTNAME: 0.0.0.0
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public:ro
    networks:
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development server with hot reload
  draftly-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: draftly-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      FAST_REFRESH: true
      CHOKIDAR_USEPOLLING: true
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - frontend-network
    profiles:
      - dev

volumes:
  node_modules:
    driver: local

networks:
  frontend-network:
    driver: bridge
